Code change for PoC (Proof of Concept) by adding owner column to _db_class table index
Changes:
- In order to avoid problems with code not related to POC, the functions that need to be changed are created by appending “_yj” postfix to their name, and called only from code related to POC.
- src/communication
  * Code using "locator_Mht_classnames" hash table by client request.
- src/compat
  * Code using the db_find_class() function.
- src/object
  * Code using the sm_find_class() function.
  * Code using the obj_find_unique() function.
  * Code using "Classname_cache" hash table in client (workspace).
- src/parser
  * Code using the pt_find_class() function.
- src/query
  * Code that uses the db_find_class() function when executing a CREATE TABLE query.
- src/storage
  * Code related to creating system tables when running the createdb utility.
- src/transaction
  * Code to add owner column to _db_class table index
  * Code using "locator_Mht_classnames" hash table by client request.

PoC (Proof of Concept) Purpose:
- After changing the code to distinguish the tables owned by the user.
- The code for passing the user name from the client to the server has not yet been changed, and the user name is hard-coded as "DBA".
- [ O ] Check if the system tables are created without any problems when creating a DB with the cretedb utility.
- [ O ] After connecting to csql standalone mode, execute SELECT query on system table.
- [ O ] After executing the CREATE TABLE query, execute SELECT query on the system table.
- [ O ] Check if the DB created with the cubrid server start command is running.
- [ X ] After connecting to csql client-server mode, execute SELECT query on system table.

$ csql -u dba demodb
No authorization privileges in effect for the database.
ERROR: No authorization privileges in effect for the database.