Merged revision(s) 47889-48522 from cubrid/trunk: [CUBRIDSUS-6555][CR] Introduce and implememnt a new function SYS_GUID() for generating random GUID. ........ [CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0382 ........ [CUBRIDSUS-14037][CR] Introduced Show critical sections statement
........
[CUBRIDSUS-9434][CR] To correct the incorrect svn manipulation by CUBRIDSUS-6555 svn-commit which overrided a file modification unexpectedly.
........
[CUBRIDSUS-12192] enhance checkdb util (check spage_header for a heap file/btree file and check page using file allocset)
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0383
........
[CUBRIDSUS-14255] fix call spage_check() function with null page pointer.
........
[CUBRIDSUS-13799][CR] fix a message to notify the number of flushed pages during checkpoint to users.
........
[CUBRIDSUS-14120][CR] eliminate the session property from client/server parameters with ER_ or CALL_ prefix.
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0384
........
[CUBRIDSUS-14247][CR]fix a bug that a certain broker gets fewer connections when using cci driver with loadbalance on
........
[CUBRIDSUS-14000][CR] fix report "undefined reference to `cci_get_cas_info' on windows." on Windows or MinGW.
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0385
........
[CUBRIDSUS-13893][CR] fix a split-brain problem when ha_node_list/ip_address is wrong or cannot resolve hostname
........
[CUBRIDSUS-13992][CR] fixed double dealloction of the same page after file_destory().
........
[CUBRIDSUS-14041][CR] Edit first leaf part in btree_build_nleafs()
........
[CUBRIDSUS-14156][CR] applylogdb write error log with ERROR severity when cannot acquire APPLYLOGDB file lock
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0386
........
[CUBRIDSUS-14238][CR] revert rev.46997 (remove dbgw build in build.sh)
........
[CUBRIDSUS-14238][CR] revert rev.47081 (remove dbgw windows install)
........
[CUBRIDSUS-13992][CR] fixed double dealloction of the same page after file_destory().
........
[CUBRIDSUS-14041][CR] Add comment in btree_build_nleafs()
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0387
........
[CUBRIDSUS-14298][CR] fix free wild pointer issue in transfer_disk_structures()
........
[CUBRIDSUS-14217][CR]sleep function support
........
[CUBRIDSUS-13844][CR] fix the bug cub_proxy makes core
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0388
........
Merged revision(s) 88191-88960 from cubrid/trunk: r88960

........
Changes:

1.
  - Fixed vacuuming reusable objects heap files.
  - Fixed calls of OR_INT_BUF2.
  - Heap files are now vacuumed immediately after finding one record for that page. Then they are collected in order to avoid re-vacuuming the same page.
  - Dropped classes and indexes are now replaced with only one routine of dropped files.
  - Tracking dropped files now use postpone and undo log records.
  - Before deallocating the pages of a file, the transaction must notify workers of the dropped files and wait until all active workers are notified.
  - Fixed vacuuming heap file overflow records.
  - Fixed missing LOG_UNDO_DATA from redo recovery.
  - Vacuum no longer accepts unexpected data in heap files and b-tree recovery data.
  - Fixed heap get internal function which didn't unfix the home page when failing conditional latch on forward page for relocation records.
  - Fixed getting stats key handling of fence keys.
  - Do not add more blocks into vacuum data if it's full.
  - Removed old logging for redo add dropped files recovery.
  - Commented the assert in clear bit and vhdr index number pages for now, until the other issues are fixed.

2. Fixed checking foreign key constraint when key is the same but the OID is changed (due to MVCC update).
3. Fixed unitialized heap when updating a big heap record and MVCC snapshot is NULL.
4. Fixed error message in heap_get_mvcc_last_version.
5. fixed CUBRIDSUS-14250, CUBRIDSUS-14147 force update in place when foreign key constraint is added
6. fixed finding OID in overflow OIDs page position 0 - vacuum needs to check INSID, DELID together with OID
7. moved heap update style (update in place or MVCC style) from  heap_update to its caller
8. Fixed redo recovery for MVCC delete relocated, for the case when the record was inserted into a new slot.
9. Fixed mr_cmpval_object function to get latest object versions before comparing OID's.
10. Modified logging of MVCC delete relocated/relocation to include record data in order to avoid recovery crashes. 2. Removed unused field mvcc_id from MVCC_RELOCATE_DELETE_INFO.
11. use snapshot dirty & locking inside btree_range_search in the following situations:   - when find foreign key   - when find unique revert btree_handle_prev_leaf_after_locking and btree_handle_curr_leaf_after_locking functions


........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0389
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.9016
........
[CUBRIDSUS-14333][CR] fixed segmentation fault when cci_schema_info request closed.
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0390
........
Patch 23_MVCC-23-07-2014.
1. Fixed assert being hit when inspection scans are used.
2. Fetch the object if decached in trigger before removing it.
3. Use update in place if the class doesn't have unique index.
4. Reflect accumulated statistics to B-trees inside of CSECT_TRAN_TABLE critical section for consistency
5. Search from previous key when resume after unconditional locking - need when insert & rollback.
6. Fix for unitialized pointer being freed.
7. Added more logging for vacuum data.
........
[CUBRIDSUS-1325][CR] DailyBuild auto increment - 10.0.0.0391
........